name = "Mavi"
uuid = "744abf98-bd76-4ff1-9030-f2bc55e921ed"
authors = ["Marcos Pasa", "Vin√≠cius"]
version = "1.0.0-DEV"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
